<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.31" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopAutomationBot.Application\DesktopAutomationBot.Application.csproj" />
    <ProjectReference Include="..\DesktopAutomationBot.Core\DesktopAutomationBot.Core.csproj" />
    <ProjectReference Include="..\DesktopAutomationBot.Web.Shared\DesktopAutomationBot.Web.Shared.csproj" />
  </ItemGroup>

</Project>
